language: generic

sudo: required

services:
  - docker

script:
  - docker build -t chltjdqh217/tripplannerz-nginx ./nginx
  - docker build -t chltjdqh217/tripplannerz-database ./postgres
  - docker build -t chltjdqh217/tripplannerz-frontend ./client
  - docker build -t chltjdqh217/tripplannerz-backend -f Dockerfile.dev ./

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push chltjdqh217/tripplannerz-nginx
  - docker push chltjdqh217/tripplannerz-frontend
  - docker push chltjdqh217/tripplannerz-backend

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "tripplannerz"
  env: "Tripplannerz-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-815860262428"
  bucket_path: "tripplannerz"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY