version: "3"

services:
#  database:
#    build: ./postgres
#    restart: unless-stopped
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./postgres/sqls:/docker-entrypoint-initdb.d
#    environment:
#      POSTGRES_USERNAME: postgres
#      POSTGRES_PASSWORD: 1234

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  cache:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./
    container_name: app_backend
    ports:
      - "8080:8080"


  frontend:
    build : ./client
    container_name: app_frontend
    stdin_open: true










